#!/bin/bash

date 

module load anaconda

conda activate ilab_clone

export LPDAAC=$(cat token)

#python MODIS_download_nc.py -t $1 -a $LPDAAC -c 61 -o $2/$1/data -dp MCD64A1 -y $2 & wait

python MODIS_download_nc.py -t $1 -a $LPDAAC -c 61 -o $2/$1/data -dp MOD09GA -y $2 & wait

# python MODIS_download_nc.py -t $1 -a $LPDAAC -c 61 -o $2/$1/data -dp MOD09GQ -y $2 & wait
